apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-minion
  name: redis-minion
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis-minion
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: redis-minion
    spec:
      containers:
        - env:
            - name: GET_HOSTS_FROM
              value: dns
          image: gcr.io/google_samples/gb-redisminion:v3
          name: redis-minion
          ports:
            - containerPort: 6379
          resources: {}
      restartPolicy: Always
status: {}
