apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: smoke-test
  name: smoke-test
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: smoke-test
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: smoke-test
    spec:
      imagePullSecrets:
        - name: dockerhub-creds
      containers:
        - name: smoke-test
          image: sureshotcapital/algo-repo:latest
          resources: {}
      restartPolicy: Always
status: {}
